### ISSUE TITLE
AsyncUDP missing when using ESP32 board

### ISSUE THREAD

**Issue by ablyler** [cbpowell/ESPSense#10]
With a platform set to esp32, you get the following error:

```
In file included from src/esphome.h:22,
                 from src/main.cpp:3:
src/esphome/components/espsense/espsense.h:12:10: fatal error: AsyncUDP.h: No such file or directory

******************************************************************
* Looking for AsyncUDP.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:AsyncUDP.h"
* Web  > https://registry.platformio.org/search?q=header:AsyncUDP.h
*
******************************************************************

 #include "AsyncUDP.h"
          ^~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/geo-panel/src/main.cpp.o] Error 1
```

**Comment by cbpowell** [comment]
Thanks for identifying this isn't working! I'm not sure the method in pull request is the way to correct this though, as that's in an autogenerated file. The `espsense.h` header file _should_ pull it in during build ([see here](https://github.com/cbpowell/ESPSense/blob/e5be82fde0760c6a2f6235a7bb4cc5e304795314/components/espsense/espsense.h#L11C8-L13)) when on an ESP32 architecture. I'll try to dig in this weekend and see what's up.

**Comment by cbpowell** [comment]
> Thanks for identifying this isn't working! I'm not sure the method in pull request is the way to correct this though, as that's in an autogenerated file. The `espsense.h` header file _should_ pull it in during build ([see here](https://github.com/cbpowell/ESPSense/blob/e5be82fde0760c6a2f6235a7bb4cc5e304795314/components/espsense/espsense.h#L11C8-L13)) when on an ESP32 architecture. I'll try to dig in this weekend and see what's up.

Whoooops I take that back, I guess it's just been long enough since I set this up that I forgot how custom components are set up. Your change is correct!

**Comment by cbpowell** [comment]
Thanks for the fix!

**Comment by ablyler** [comment]
Thanks for the quick review and merge! I totally understand the confusion around whether this is the right way to fix it or not. It took me a while to wrap my head around it.
