### ISSUE TITLE
Ghome discovery 

### ISSUE THREAD

**Issue by beckmx** [cbpowell/ESPSense#5]
Hello, i was wondering if you know how the seamless integration with google home works, i scanned using google home and discovered the device but requested either a qr code or 8 digit code

**Comment by cbpowell** [comment]
Hey - sorry, no idea! Don’t have any Google Home products myself. ESPSense implements _some_ of the features of a real TP-Link energy monitoring plug, so I’m guessing Google Home queries for them somehow?

But it doesn’t provide some of the other standard features of TP-Link, like actual control of the plug via that API. So it’s unlikely to work well with Google Home.
