### ISSUE TITLE
External Component

### ISSUE THREAD

**Issue by nuttytree** [cbpowell/ESPSense#6]
Any plans to make this an ESPHome [external component](https://esphome.io/components/external_components.html)?  Or even better yet make this part of the core ESPHome code?  Making this an external component would simplify using this and keeping up to date on code changes. I can volunteer to do the work to make it an external component if you want.

**Comment by cbpowell** [comment]
Wow somehow I'd totally missed that external components existed. That sounds like a good first step, and would certainly appreciate your help to get it set up!

I'm not familiar with what it takes to get something incorporated into core but I would certainly support that too.

**Comment by nuttytree** [comment]
I would say the first step is to get it built as an external component as the setup for that is essentially the same as a component in the core code.  I can try and get a PR up for that in the next couple of days.  After that there will probably be some formatting and minor design tweaks (to get the code in the same style as ESPHome) and making sure it is pretty much rock solid.  It will probably be worth having a conversation with @jesserockz and/or @OttoWinter before submitting a PR for ESPHome to make sure they are on board with the concept and to make sure they aren't already doing something similar (energy monitoring looks to be a big focus now).

**Comment by jesserockz** [comment]
No plans for doing this kind of thing from our side. I have not looked at the code yet so can't comment on what its doing. Will take a look when i get a chance.

**Comment by cbpowell** [comment]
Hmm true, SenseLink prevents you from using the same MAC twice within the same instance ([see here](https://github.com/cbpowell/SenseLink/blob/a5c2b7fed66e216bfa9cc0b086f0bcd8549a395f/SenseLink.py#L153-L162)) but I didn't add that here. The analogous approach would be to check the MAC against the existing plugs in `addPlug()`.

Probably out of scope to _broadly_ prevent someone from using the same MAC twice on two different ESPHome configs? Other than with a warning in the docs. But yeah it definitely gives some weird behavior.

**Comment by nuttytree** [comment]
PR is up, I tried to keep any code refactoring to a minimum and focus on what was needed to make it an external component.

**Comment by cbpowell** [comment]
Awesome! Thanks for putting it together, I'll check it out by this weekend if not sooner.

**Comment by cbpowell** [comment]
Resolved by #7. Thanks @nuttytree!
